name: CI

on:
  push:
    branches:    
      - master
      - ci/**

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.1.app'
    - name: Build iOS
      run: xcodebuild -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" -scheme "Harvest-SwiftUI-Gallery" build
